# Generated by Django 4.1.2 on 2022-10-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_names', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('machine_id', models.CharField(max_length=255)),
                ('availability', models.TextField()),
                ('date', models.DateField()),
                ('time_in', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'time_in',
            },
        ),
    ]
